### ISSUE TITLE
🤣🤣🤣

### ISSUE THREAD

**Issue by 0xMenkoh** [C4lme/Nft-Drainer-template#1]
hahahaa nice try babe

**Comment by C4lme** [comment]
Hello, what’s the issue?

**Comment by 0xMenkoh** [comment]
nice try but be careful, the index can be easily deobfuscated and we will see your beautiful wallet

**Comment by C4lme** [comment]
not at all, did you even try the script?

**Comment by C4lme** [comment]
it only send to the one from the configuration

**Comment by C4lme** [comment]
I can understand that you’re mad because you didn’t code this shit and you’re selling it for 100$.
All credits goes OlaServices for the code.
